// Generated by shared/ui-layout/tools/generate-ui-layout-contract.ts.
// Do not edit by hand.

#ifndef SILENCER_NET_UI_LAYOUT_CONTRACT_GENERATED_H
#define SILENCER_NET_UI_LAYOUT_CONTRACT_GENERATED_H

#include <cstddef>

namespace silencer {
namespace net {
namespace ui_layout_contract {

constexpr const char * kNodeKinds[] = {
	"screen",
	"panel",
	"stack",
	"row",
	"text",
	"button",
	"spacer",
	"component",
};
constexpr std::size_t kNodeKindsCount = 8;
constexpr const char * kNodeKindScreen = "screen";
constexpr const char * kNodeKindPanel = "panel";
constexpr const char * kNodeKindStack = "stack";
constexpr const char * kNodeKindRow = "row";
constexpr const char * kNodeKindText = "text";
constexpr const char * kNodeKindButton = "button";
constexpr const char * kNodeKindSpacer = "spacer";
constexpr const char * kNodeKindComponent = "component";

constexpr const char * kContainerNodeKinds[] = {
	"screen",
	"panel",
	"stack",
	"row",
};
constexpr std::size_t kContainerNodeKindsCount = 4;
constexpr const char * kContainerNodeKindScreen = "screen";
constexpr const char * kContainerNodeKindPanel = "panel";
constexpr const char * kContainerNodeKindStack = "stack";
constexpr const char * kContainerNodeKindRow = "row";

constexpr const char * kDocumentFields[] = {
	"schemaVersion",
	"surface",
	"viewport",
	"root",
};
constexpr std::size_t kDocumentFieldsCount = 4;

constexpr const char * kViewportFields[] = {
	"width",
	"height",
};
constexpr std::size_t kViewportFieldsCount = 2;

constexpr const char * kNodeFields[] = {
	"id",
	"kind",
	"name",
	"text",
	"action",
	"textBinding",
	"component",
	"buttonVariant",
	"buttonSize",
	"image",
	"floating",
	"style",
	"children",
};
constexpr std::size_t kNodeFieldsCount = 13;

constexpr const char * kSizeFields[] = {
	"mode",
	"value",
	"min",
	"max",
};
constexpr std::size_t kSizeFieldsCount = 4;

constexpr const char * kImageFields[] = {
	"bank",
	"index",
	"mode",
};
constexpr std::size_t kImageFieldsCount = 3;

constexpr const char * kFloatingFields[] = {
	"attachTo",
	"elementAttach",
	"parentAttach",
	"offsetX",
	"offsetY",
	"zIndex",
	"pointerPassthrough",
};
constexpr std::size_t kFloatingFieldsCount = 7;

constexpr const char * kAxes[] = {
	"column",
	"row",
};
constexpr std::size_t kAxesCount = 2;
constexpr const char * kAxisColumn = "column";
constexpr const char * kAxisRow = "row";

constexpr const char * kAligns[] = {
	"start",
	"center",
	"end",
};
constexpr std::size_t kAlignsCount = 3;
constexpr const char * kAlignStart = "start";
constexpr const char * kAlignCenter = "center";
constexpr const char * kAlignEnd = "end";

constexpr const char * kJustifies[] = {
	"start",
	"center",
	"end",
};
constexpr std::size_t kJustifiesCount = 3;
constexpr const char * kJustifyStart = "start";
constexpr const char * kJustifyCenter = "center";
constexpr const char * kJustifyEnd = "end";

constexpr const char * kSizeModes[] = {
	"fit",
	"grow",
	"fixed",
};
constexpr std::size_t kSizeModesCount = 3;
constexpr const char * kSizeModeFit = "fit";
constexpr const char * kSizeModeGrow = "grow";
constexpr const char * kSizeModeFixed = "fixed";

constexpr const char * kFonts[] = {
	"ui",
	"uiLarge",
	"title",
	"tiny",
	"footer",
};
constexpr std::size_t kFontsCount = 5;
constexpr const char * kFontUi = "ui";
constexpr const char * kFontUiLarge = "uiLarge";
constexpr const char * kFontTitle = "title";
constexpr const char * kFontTiny = "tiny";
constexpr const char * kFontFooter = "footer";

constexpr const char * kButtonVariants[] = {
	"oval",
	"chrome",
	"text",
	"ghost",
};
constexpr std::size_t kButtonVariantsCount = 4;
constexpr const char * kButtonVariantOval = "oval";
constexpr const char * kButtonVariantChrome = "chrome";
constexpr const char * kButtonVariantText = "text";
constexpr const char * kButtonVariantGhost = "ghost";

constexpr const char * kButtonSizes[] = {
	"sm",
	"md",
	"lg",
	"compact",
	"auto",
};
constexpr std::size_t kButtonSizesCount = 5;
constexpr const char * kButtonSizeSm = "sm";
constexpr const char * kButtonSizeMd = "md";
constexpr const char * kButtonSizeLg = "lg";
constexpr const char * kButtonSizeCompact = "compact";
constexpr const char * kButtonSizeAuto = "auto";

constexpr const char * kImageModes[] = {
	"normal",
	"contain",
	"stretch",
};
constexpr std::size_t kImageModesCount = 3;
constexpr const char * kImageModeNormal = "normal";
constexpr const char * kImageModeContain = "contain";
constexpr const char * kImageModeStretch = "stretch";

constexpr const char * kAttachToValues[] = {
	"parent",
	"root",
};
constexpr std::size_t kAttachToValuesCount = 2;
constexpr const char * kAttachToParent = "parent";
constexpr const char * kAttachToRoot = "root";

constexpr const char * kAttachPoints[] = {
	"left-top",
	"left-center",
	"left-bottom",
	"center-top",
	"center",
	"center-bottom",
	"right-top",
	"right-center",
	"right-bottom",
};
constexpr std::size_t kAttachPointsCount = 9;
constexpr const char * kAttachPointLeftTop = "left-top";
constexpr const char * kAttachPointLeftCenter = "left-center";
constexpr const char * kAttachPointLeftBottom = "left-bottom";
constexpr const char * kAttachPointCenterTop = "center-top";
constexpr const char * kAttachPointCenter = "center";
constexpr const char * kAttachPointCenterBottom = "center-bottom";
constexpr const char * kAttachPointRightTop = "right-top";
constexpr const char * kAttachPointRightCenter = "right-center";
constexpr const char * kAttachPointRightBottom = "right-bottom";

constexpr const char * kScreenStyleFields[] = {
	"width",
	"height",
	"direction",
	"align",
	"justify",
	"padding",
	"gap",
	"backgroundPalette",
	"borderPalette",
	"radius",
};
constexpr std::size_t kScreenStyleFieldsCount = 10;

constexpr const char * kPanelStyleFields[] = {
	"width",
	"height",
	"direction",
	"align",
	"justify",
	"padding",
	"gap",
	"backgroundPalette",
	"borderPalette",
	"radius",
};
constexpr std::size_t kPanelStyleFieldsCount = 10;

constexpr const char * kStackStyleFields[] = {
	"width",
	"height",
	"direction",
	"align",
	"justify",
	"padding",
	"gap",
	"backgroundPalette",
	"borderPalette",
	"radius",
};
constexpr std::size_t kStackStyleFieldsCount = 10;

constexpr const char * kRowStyleFields[] = {
	"width",
	"height",
	"direction",
	"align",
	"justify",
	"padding",
	"gap",
	"backgroundPalette",
	"borderPalette",
	"radius",
};
constexpr std::size_t kRowStyleFieldsCount = 10;

constexpr const char * kTextStyleFields[] = {
	"width",
	"height",
	"padding",
	"backgroundPalette",
	"borderPalette",
	"textPalette",
	"font",
	"radius",
};
constexpr std::size_t kTextStyleFieldsCount = 8;

constexpr const char * kButtonStyleFields[] = {
	"width",
	"height",
	"padding",
	"textPalette",
};
constexpr std::size_t kButtonStyleFieldsCount = 4;

constexpr const char * kSpacerStyleFields[] = {
	"width",
	"height",
};
constexpr std::size_t kSpacerStyleFieldsCount = 2;

constexpr const char * kComponentStyleFields[] = {
	"width",
	"height",
};
constexpr std::size_t kComponentStyleFieldsCount = 2;

struct StyleFieldsForKind {
	const char * kind;
	const char * const * fields;
	std::size_t fieldCount;
};

constexpr StyleFieldsForKind kStyleFieldsByKind[] = {
	{ "screen", kScreenStyleFields, kScreenStyleFieldsCount },
	{ "panel", kPanelStyleFields, kPanelStyleFieldsCount },
	{ "stack", kStackStyleFields, kStackStyleFieldsCount },
	{ "row", kRowStyleFields, kRowStyleFieldsCount },
	{ "text", kTextStyleFields, kTextStyleFieldsCount },
	{ "button", kButtonStyleFields, kButtonStyleFieldsCount },
	{ "spacer", kSpacerStyleFields, kSpacerStyleFieldsCount },
	{ "component", kComponentStyleFields, kComponentStyleFieldsCount },
};
constexpr std::size_t kStyleFieldsByKindCount = 8;

}  // namespace ui_layout_contract
}  // namespace net
}  // namespace silencer

#endif
