// Generated by shared/ui-layout/tools/generate-ui-layout-contract.ts.
// Do not edit by hand.

#ifndef SILENCER_NET_UI_LAYOUT_CONTRACT_GENERATED_H
#define SILENCER_NET_UI_LAYOUT_CONTRACT_GENERATED_H

#include <cstddef>

namespace silencer {
namespace net {
namespace ui_layout_contract {

constexpr const char * kNodeKinds[] = {
	"screen",
	"panel",
	"stack",
	"row",
	"text",
	"button",
	"spacer",
	"component",
};
constexpr std::size_t kNodeKindsCount = 8;

constexpr const char * kContainerNodeKinds[] = {
	"screen",
	"panel",
	"stack",
	"row",
};
constexpr std::size_t kContainerNodeKindsCount = 4;

constexpr const char * kDocumentFields[] = {
	"schemaVersion",
	"surface",
	"viewport",
	"root",
};
constexpr std::size_t kDocumentFieldsCount = 4;

constexpr const char * kViewportFields[] = {
	"width",
	"height",
};
constexpr std::size_t kViewportFieldsCount = 2;

constexpr const char * kNodeFields[] = {
	"id",
	"kind",
	"name",
	"text",
	"action",
	"textBinding",
	"component",
	"buttonVariant",
	"buttonSize",
	"image",
	"floating",
	"style",
	"children",
};
constexpr std::size_t kNodeFieldsCount = 13;

constexpr const char * kSizeFields[] = {
	"mode",
	"value",
	"min",
	"max",
};
constexpr std::size_t kSizeFieldsCount = 4;

constexpr const char * kImageFields[] = {
	"bank",
	"index",
	"mode",
};
constexpr std::size_t kImageFieldsCount = 3;

constexpr const char * kFloatingFields[] = {
	"attachTo",
	"elementAttach",
	"parentAttach",
	"offsetX",
	"offsetY",
	"zIndex",
	"pointerPassthrough",
};
constexpr std::size_t kFloatingFieldsCount = 7;

constexpr const char * kScreenStyleFields[] = {
	"width",
	"height",
	"direction",
	"align",
	"justify",
	"padding",
	"gap",
	"backgroundPalette",
	"borderPalette",
	"radius",
};
constexpr std::size_t kScreenStyleFieldsCount = 10;

constexpr const char * kPanelStyleFields[] = {
	"width",
	"height",
	"direction",
	"align",
	"justify",
	"padding",
	"gap",
	"backgroundPalette",
	"borderPalette",
	"radius",
};
constexpr std::size_t kPanelStyleFieldsCount = 10;

constexpr const char * kStackStyleFields[] = {
	"width",
	"height",
	"direction",
	"align",
	"justify",
	"padding",
	"gap",
	"backgroundPalette",
	"borderPalette",
	"radius",
};
constexpr std::size_t kStackStyleFieldsCount = 10;

constexpr const char * kRowStyleFields[] = {
	"width",
	"height",
	"direction",
	"align",
	"justify",
	"padding",
	"gap",
	"backgroundPalette",
	"borderPalette",
	"radius",
};
constexpr std::size_t kRowStyleFieldsCount = 10;

constexpr const char * kTextStyleFields[] = {
	"width",
	"height",
	"padding",
	"backgroundPalette",
	"borderPalette",
	"textPalette",
	"font",
	"radius",
};
constexpr std::size_t kTextStyleFieldsCount = 8;

constexpr const char * kButtonStyleFields[] = {
	"width",
	"height",
	"padding",
	"textPalette",
};
constexpr std::size_t kButtonStyleFieldsCount = 4;

constexpr const char * kSpacerStyleFields[] = {
	"width",
	"height",
};
constexpr std::size_t kSpacerStyleFieldsCount = 2;

constexpr const char * kComponentStyleFields[] = {
	"width",
	"height",
};
constexpr std::size_t kComponentStyleFieldsCount = 2;

struct StyleFieldsForKind {
	const char * kind;
	const char * const * fields;
	std::size_t fieldCount;
};

constexpr StyleFieldsForKind kStyleFieldsByKind[] = {
	{ "screen", kScreenStyleFields, kScreenStyleFieldsCount },
	{ "panel", kPanelStyleFields, kPanelStyleFieldsCount },
	{ "stack", kStackStyleFields, kStackStyleFieldsCount },
	{ "row", kRowStyleFields, kRowStyleFieldsCount },
	{ "text", kTextStyleFields, kTextStyleFieldsCount },
	{ "button", kButtonStyleFields, kButtonStyleFieldsCount },
	{ "spacer", kSpacerStyleFields, kSpacerStyleFieldsCount },
	{ "component", kComponentStyleFields, kComponentStyleFieldsCount },
};
constexpr std::size_t kStyleFieldsByKindCount = 8;

}  // namespace ui_layout_contract
}  // namespace net
}  // namespace silencer

#endif
