// Generated by shared/ui-layout/tools/generate-ui-layout-contract.ts.
// Do not edit by hand.

#ifndef SILENCER_NET_UI_LAYOUT_CONTRACT_GENERATED_H
#define SILENCER_NET_UI_LAYOUT_CONTRACT_GENERATED_H

#include <cstddef>

namespace silencer {
namespace net {
namespace ui_layout_contract {

constexpr int kSchemaVersion = 1;
constexpr int kMinViewport = 160;
constexpr int kMaxViewport = 4096;
constexpr float kMinSize = 0.0f;
constexpr float kMaxSize = 4096.0f;
constexpr int kMinPadding = 0;
constexpr int kMaxPadding = 512;
constexpr int kMinGap = 0;
constexpr int kMaxGap = 512;
constexpr int kMinRadius = 0;
constexpr int kMaxRadius = 64;
constexpr int kMinPalette = -1;
constexpr int kMinTextPalette = 0;
constexpr int kMaxPalette = 255;
constexpr int kMinImageBank = 0;
constexpr int kMaxImageBank = 255;
constexpr int kMinImageIndex = 0;
constexpr int kMaxImageIndex = 65535;
constexpr float kMinFloatingOffset = -4096.0f;
constexpr float kMaxFloatingOffset = 4096.0f;
constexpr int kMinFloatingZIndex = -32768;
constexpr int kMaxFloatingZIndex = 32767;

constexpr const char * kNodeKinds[] = {
	"screen",
	"panel",
	"stack",
	"row",
	"text",
	"button",
	"spacer",
	"component",
};
constexpr std::size_t kNodeKindsCount = 8;
constexpr const char * kNodeKindScreen = "screen";
constexpr const char * kNodeKindPanel = "panel";
constexpr const char * kNodeKindStack = "stack";
constexpr const char * kNodeKindRow = "row";
constexpr const char * kNodeKindText = "text";
constexpr const char * kNodeKindButton = "button";
constexpr const char * kNodeKindSpacer = "spacer";
constexpr const char * kNodeKindComponent = "component";

constexpr const char * kContainerNodeKinds[] = {
	"screen",
	"panel",
	"stack",
	"row",
};
constexpr std::size_t kContainerNodeKindsCount = 4;
constexpr const char * kContainerNodeKindScreen = "screen";
constexpr const char * kContainerNodeKindPanel = "panel";
constexpr const char * kContainerNodeKindStack = "stack";
constexpr const char * kContainerNodeKindRow = "row";

constexpr const char * kDocumentFields[] = {
	"schemaVersion",
	"surface",
	"viewport",
	"root",
};
constexpr std::size_t kDocumentFieldsCount = 4;

constexpr const char * kViewportFields[] = {
	"width",
	"height",
};
constexpr std::size_t kViewportFieldsCount = 2;

constexpr const char * kNodeFields[] = {
	"id",
	"kind",
	"name",
	"text",
	"action",
	"textBinding",
	"component",
	"buttonVariant",
	"buttonSize",
	"image",
	"floating",
	"style",
	"children",
};
constexpr std::size_t kNodeFieldsCount = 13;

constexpr const char * kSizeFields[] = {
	"mode",
	"value",
	"min",
	"max",
};
constexpr std::size_t kSizeFieldsCount = 4;

constexpr const char * kImageFields[] = {
	"bank",
	"index",
	"mode",
};
constexpr std::size_t kImageFieldsCount = 3;

constexpr const char * kFloatingFields[] = {
	"attachTo",
	"elementAttach",
	"parentAttach",
	"offsetX",
	"offsetY",
	"zIndex",
	"pointerPassthrough",
};
constexpr std::size_t kFloatingFieldsCount = 7;

constexpr const char * kAxes[] = {
	"column",
	"row",
};
constexpr std::size_t kAxesCount = 2;
constexpr const char * kAxisColumn = "column";
constexpr const char * kAxisRow = "row";

constexpr const char * kAligns[] = {
	"start",
	"center",
	"end",
};
constexpr std::size_t kAlignsCount = 3;
constexpr const char * kAlignStart = "start";
constexpr const char * kAlignCenter = "center";
constexpr const char * kAlignEnd = "end";

constexpr const char * kJustifies[] = {
	"start",
	"center",
	"end",
};
constexpr std::size_t kJustifiesCount = 3;
constexpr const char * kJustifyStart = "start";
constexpr const char * kJustifyCenter = "center";
constexpr const char * kJustifyEnd = "end";

constexpr const char * kSizeModes[] = {
	"fit",
	"grow",
	"fixed",
};
constexpr std::size_t kSizeModesCount = 3;
constexpr const char * kSizeModeFit = "fit";
constexpr const char * kSizeModeGrow = "grow";
constexpr const char * kSizeModeFixed = "fixed";

constexpr const char * kFonts[] = {
	"ui",
	"uiLarge",
	"title",
	"tiny",
	"footer",
};
constexpr std::size_t kFontsCount = 5;
constexpr const char * kFontUi = "ui";
constexpr const char * kFontUiLarge = "uiLarge";
constexpr const char * kFontTitle = "title";
constexpr const char * kFontTiny = "tiny";
constexpr const char * kFontFooter = "footer";

constexpr const char * kButtonVariants[] = {
	"oval",
	"chrome",
	"text",
	"ghost",
};
constexpr std::size_t kButtonVariantsCount = 4;
constexpr const char * kButtonVariantOval = "oval";
constexpr const char * kButtonVariantChrome = "chrome";
constexpr const char * kButtonVariantText = "text";
constexpr const char * kButtonVariantGhost = "ghost";

constexpr const char * kButtonSizes[] = {
	"sm",
	"md",
	"lg",
	"compact",
	"auto",
};
constexpr std::size_t kButtonSizesCount = 5;
constexpr const char * kButtonSizeSm = "sm";
constexpr const char * kButtonSizeMd = "md";
constexpr const char * kButtonSizeLg = "lg";
constexpr const char * kButtonSizeCompact = "compact";
constexpr const char * kButtonSizeAuto = "auto";

constexpr const char * kImageModes[] = {
	"normal",
	"contain",
	"stretch",
};
constexpr std::size_t kImageModesCount = 3;
constexpr const char * kImageModeNormal = "normal";
constexpr const char * kImageModeContain = "contain";
constexpr const char * kImageModeStretch = "stretch";

constexpr const char * kAttachToValues[] = {
	"parent",
	"root",
};
constexpr std::size_t kAttachToValuesCount = 2;
constexpr const char * kAttachToParent = "parent";
constexpr const char * kAttachToRoot = "root";

constexpr const char * kAttachPoints[] = {
	"left-top",
	"left-center",
	"left-bottom",
	"center-top",
	"center",
	"center-bottom",
	"right-top",
	"right-center",
	"right-bottom",
};
constexpr std::size_t kAttachPointsCount = 9;
constexpr const char * kAttachPointLeftTop = "left-top";
constexpr const char * kAttachPointLeftCenter = "left-center";
constexpr const char * kAttachPointLeftBottom = "left-bottom";
constexpr const char * kAttachPointCenterTop = "center-top";
constexpr const char * kAttachPointCenter = "center";
constexpr const char * kAttachPointCenterBottom = "center-bottom";
constexpr const char * kAttachPointRightTop = "right-top";
constexpr const char * kAttachPointRightCenter = "right-center";
constexpr const char * kAttachPointRightBottom = "right-bottom";

constexpr const char * kScreenStyleFields[] = {
	"width",
	"height",
	"direction",
	"align",
	"justify",
	"padding",
	"gap",
	"backgroundPalette",
	"borderPalette",
	"radius",
};
constexpr std::size_t kScreenStyleFieldsCount = 10;

constexpr const char * kPanelStyleFields[] = {
	"width",
	"height",
	"direction",
	"align",
	"justify",
	"padding",
	"gap",
	"backgroundPalette",
	"borderPalette",
	"radius",
};
constexpr std::size_t kPanelStyleFieldsCount = 10;

constexpr const char * kStackStyleFields[] = {
	"width",
	"height",
	"direction",
	"align",
	"justify",
	"padding",
	"gap",
	"backgroundPalette",
	"borderPalette",
	"radius",
};
constexpr std::size_t kStackStyleFieldsCount = 10;

constexpr const char * kRowStyleFields[] = {
	"width",
	"height",
	"direction",
	"align",
	"justify",
	"padding",
	"gap",
	"backgroundPalette",
	"borderPalette",
	"radius",
};
constexpr std::size_t kRowStyleFieldsCount = 10;

constexpr const char * kTextStyleFields[] = {
	"width",
	"height",
	"padding",
	"backgroundPalette",
	"borderPalette",
	"textPalette",
	"font",
	"radius",
};
constexpr std::size_t kTextStyleFieldsCount = 8;

constexpr const char * kButtonStyleFields[] = {
	"width",
	"height",
	"padding",
	"textPalette",
};
constexpr std::size_t kButtonStyleFieldsCount = 4;

constexpr const char * kSpacerStyleFields[] = {
	"width",
	"height",
};
constexpr std::size_t kSpacerStyleFieldsCount = 2;

constexpr const char * kComponentStyleFields[] = {
	"width",
	"height",
};
constexpr std::size_t kComponentStyleFieldsCount = 2;

struct StyleFieldsForKind {
	const char * kind;
	const char * const * fields;
	std::size_t fieldCount;
};

constexpr StyleFieldsForKind kStyleFieldsByKind[] = {
	{ "screen", kScreenStyleFields, kScreenStyleFieldsCount },
	{ "panel", kPanelStyleFields, kPanelStyleFieldsCount },
	{ "stack", kStackStyleFields, kStackStyleFieldsCount },
	{ "row", kRowStyleFields, kRowStyleFieldsCount },
	{ "text", kTextStyleFields, kTextStyleFieldsCount },
	{ "button", kButtonStyleFields, kButtonStyleFieldsCount },
	{ "spacer", kSpacerStyleFields, kSpacerStyleFieldsCount },
	{ "component", kComponentStyleFields, kComponentStyleFieldsCount },
};
constexpr std::size_t kStyleFieldsByKindCount = 8;

struct StringListForKind {
	const char * kind;
	const char * const * values;
	std::size_t valueCount;
};

constexpr const char * kNodeTokenFieldsScreen[] = {
	nullptr,
};
constexpr std::size_t kNodeTokenFieldsScreenCount = 0;

constexpr const char * kNodeTokenFieldsPanel[] = {
	nullptr,
};
constexpr std::size_t kNodeTokenFieldsPanelCount = 0;

constexpr const char * kNodeTokenFieldsStack[] = {
	nullptr,
};
constexpr std::size_t kNodeTokenFieldsStackCount = 0;

constexpr const char * kNodeTokenFieldsRow[] = {
	nullptr,
};
constexpr std::size_t kNodeTokenFieldsRowCount = 0;

constexpr const char * kNodeTokenFieldsText[] = {
	"text",
	"textBinding",
};
constexpr std::size_t kNodeTokenFieldsTextCount = 2;

constexpr const char * kNodeTokenFieldsButton[] = {
	"text",
	"textBinding",
	"action",
	"buttonVariant",
	"buttonSize",
};
constexpr std::size_t kNodeTokenFieldsButtonCount = 5;

constexpr const char * kNodeTokenFieldsSpacer[] = {
	nullptr,
};
constexpr std::size_t kNodeTokenFieldsSpacerCount = 0;

constexpr const char * kNodeTokenFieldsComponent[] = {
	"component",
};
constexpr std::size_t kNodeTokenFieldsComponentCount = 1;

constexpr StringListForKind kNodeTokenFieldsByKind[] = {
	{ "screen", kNodeTokenFieldsScreen, kNodeTokenFieldsScreenCount },
	{ "panel", kNodeTokenFieldsPanel, kNodeTokenFieldsPanelCount },
	{ "stack", kNodeTokenFieldsStack, kNodeTokenFieldsStackCount },
	{ "row", kNodeTokenFieldsRow, kNodeTokenFieldsRowCount },
	{ "text", kNodeTokenFieldsText, kNodeTokenFieldsTextCount },
	{ "button", kNodeTokenFieldsButton, kNodeTokenFieldsButtonCount },
	{ "spacer", kNodeTokenFieldsSpacer, kNodeTokenFieldsSpacerCount },
	{ "component", kNodeTokenFieldsComponent, kNodeTokenFieldsComponentCount },
};
constexpr std::size_t kNodeTokenFieldsByKindCount = 8;

constexpr const char * kRequiredTokenFieldsScreen[] = {
	nullptr,
};
constexpr std::size_t kRequiredTokenFieldsScreenCount = 0;

constexpr const char * kRequiredTokenFieldsPanel[] = {
	nullptr,
};
constexpr std::size_t kRequiredTokenFieldsPanelCount = 0;

constexpr const char * kRequiredTokenFieldsStack[] = {
	nullptr,
};
constexpr std::size_t kRequiredTokenFieldsStackCount = 0;

constexpr const char * kRequiredTokenFieldsRow[] = {
	nullptr,
};
constexpr std::size_t kRequiredTokenFieldsRowCount = 0;

constexpr const char * kRequiredTokenFieldsText[] = {
	nullptr,
};
constexpr std::size_t kRequiredTokenFieldsTextCount = 0;

constexpr const char * kRequiredTokenFieldsButton[] = {
	nullptr,
};
constexpr std::size_t kRequiredTokenFieldsButtonCount = 0;

constexpr const char * kRequiredTokenFieldsSpacer[] = {
	nullptr,
};
constexpr std::size_t kRequiredTokenFieldsSpacerCount = 0;

constexpr const char * kRequiredTokenFieldsComponent[] = {
	"component",
};
constexpr std::size_t kRequiredTokenFieldsComponentCount = 1;

constexpr StringListForKind kRequiredTokenFieldsByKind[] = {
	{ "screen", kRequiredTokenFieldsScreen, kRequiredTokenFieldsScreenCount },
	{ "panel", kRequiredTokenFieldsPanel, kRequiredTokenFieldsPanelCount },
	{ "stack", kRequiredTokenFieldsStack, kRequiredTokenFieldsStackCount },
	{ "row", kRequiredTokenFieldsRow, kRequiredTokenFieldsRowCount },
	{ "text", kRequiredTokenFieldsText, kRequiredTokenFieldsTextCount },
	{ "button", kRequiredTokenFieldsButton, kRequiredTokenFieldsButtonCount },
	{ "spacer", kRequiredTokenFieldsSpacer, kRequiredTokenFieldsSpacerCount },
	{ "component", kRequiredTokenFieldsComponent, kRequiredTokenFieldsComponentCount },
};
constexpr std::size_t kRequiredTokenFieldsByKindCount = 8;

constexpr const char * kForbiddenNodeDecoratorsScreen[] = {
	nullptr,
};
constexpr std::size_t kForbiddenNodeDecoratorsScreenCount = 0;

constexpr const char * kForbiddenNodeDecoratorsPanel[] = {
	nullptr,
};
constexpr std::size_t kForbiddenNodeDecoratorsPanelCount = 0;

constexpr const char * kForbiddenNodeDecoratorsStack[] = {
	nullptr,
};
constexpr std::size_t kForbiddenNodeDecoratorsStackCount = 0;

constexpr const char * kForbiddenNodeDecoratorsRow[] = {
	nullptr,
};
constexpr std::size_t kForbiddenNodeDecoratorsRowCount = 0;

constexpr const char * kForbiddenNodeDecoratorsText[] = {
	nullptr,
};
constexpr std::size_t kForbiddenNodeDecoratorsTextCount = 0;

constexpr const char * kForbiddenNodeDecoratorsButton[] = {
	"image",
	"floating",
};
constexpr std::size_t kForbiddenNodeDecoratorsButtonCount = 2;

constexpr const char * kForbiddenNodeDecoratorsSpacer[] = {
	nullptr,
};
constexpr std::size_t kForbiddenNodeDecoratorsSpacerCount = 0;

constexpr const char * kForbiddenNodeDecoratorsComponent[] = {
	nullptr,
};
constexpr std::size_t kForbiddenNodeDecoratorsComponentCount = 0;

constexpr StringListForKind kForbiddenNodeDecoratorsByKind[] = {
	{ "screen", kForbiddenNodeDecoratorsScreen, kForbiddenNodeDecoratorsScreenCount },
	{ "panel", kForbiddenNodeDecoratorsPanel, kForbiddenNodeDecoratorsPanelCount },
	{ "stack", kForbiddenNodeDecoratorsStack, kForbiddenNodeDecoratorsStackCount },
	{ "row", kForbiddenNodeDecoratorsRow, kForbiddenNodeDecoratorsRowCount },
	{ "text", kForbiddenNodeDecoratorsText, kForbiddenNodeDecoratorsTextCount },
	{ "button", kForbiddenNodeDecoratorsButton, kForbiddenNodeDecoratorsButtonCount },
	{ "spacer", kForbiddenNodeDecoratorsSpacer, kForbiddenNodeDecoratorsSpacerCount },
	{ "component", kForbiddenNodeDecoratorsComponent, kForbiddenNodeDecoratorsComponentCount },
};
constexpr std::size_t kForbiddenNodeDecoratorsByKindCount = 8;

constexpr const char * kButtonWidthAllowedSizeModes[] = {
	"fit",
	"fixed",
};
constexpr std::size_t kButtonWidthAllowedSizeModesCount = 2;

constexpr const char * kButtonHeightAllowedSizeModes[] = {
	"fit",
};
constexpr std::size_t kButtonHeightAllowedSizeModesCount = 1;

struct SizeRuleForKind {
	const char * kind;
	const char * axis;
	const char * const * modes;
	std::size_t modeCount;
	bool allowBounds;
};

constexpr SizeRuleForKind kSizeRulesByKind[] = {
	{ "button", "width", kButtonWidthAllowedSizeModes, kButtonWidthAllowedSizeModesCount, false },
	{ "button", "height", kButtonHeightAllowedSizeModes, kButtonHeightAllowedSizeModesCount, false },
};
constexpr std::size_t kSizeRulesByKindCount = 2;

constexpr const char * kUiSurfaces[] = {
	"main-menu",
	"options",
	"options-display",
	"options-audio",
};
constexpr std::size_t kUiSurfacesCount = 4;
constexpr const char * kUiSurfaceMainMenu = "main-menu";
constexpr const char * kUiSurfaceOptions = "options";
constexpr const char * kUiSurfaceOptionsDisplay = "options-display";
constexpr const char * kUiSurfaceOptionsAudio = "options-audio";

constexpr const char * kUiComponentMainMenuLogo = "main-menu.logo";
constexpr const char * kUiComponentOptionsDisplayFullscreenIndicator = "options_display.fullscreen_indicator";
constexpr const char * kUiComponentOptionsDisplaySmoothScalingIndicator = "options_display.smooth_scaling_indicator";
constexpr const char * kUiComponentOptionsAudioMusicIndicator = "options_audio.music_indicator";
constexpr const char * kUiTextBindingClientVersion = "client.version";
constexpr const char * kUiActionMainMenuTutorial = "main_menu.tutorial";
constexpr const char * kUiActionMainMenuLobby = "main_menu.lobby";
constexpr const char * kUiActionMainMenuOptions = "main_menu.options";
constexpr const char * kUiActionMainMenuExit = "main_menu.exit";
constexpr const char * kUiActionOptionsControls = "options.controls";
constexpr const char * kUiActionOptionsDisplay = "options.display";
constexpr const char * kUiActionOptionsAudio = "options.audio";
constexpr const char * kUiActionOptionsBack = "options.back";
constexpr const char * kUiActionOptionsDisplayFullscreen = "options_display.fullscreen";
constexpr const char * kUiActionOptionsDisplaySmoothScaling = "options_display.smooth_scaling";
constexpr const char * kUiActionOptionsDisplaySave = "options_display.save";
constexpr const char * kUiActionOptionsDisplayCancel = "options_display.cancel";
constexpr const char * kUiActionOptionsAudioMusic = "options_audio.music";
constexpr const char * kUiActionOptionsAudioSave = "options_audio.save";
constexpr const char * kUiActionOptionsAudioCancel = "options_audio.cancel";

constexpr const char * kMainMenuComponents[] = {
	"main-menu.logo",
};
constexpr std::size_t kMainMenuComponentsCount = 1;

constexpr const char * kMainMenuTextBindings[] = {
	"client.version",
};
constexpr std::size_t kMainMenuTextBindingsCount = 1;

constexpr const char * kMainMenuActions[] = {
	"main_menu.tutorial",
	"main_menu.lobby",
	"main_menu.options",
	"main_menu.exit",
};
constexpr std::size_t kMainMenuActionsCount = 4;

constexpr const char * kOptionsComponents[] = {
	nullptr,
};
constexpr std::size_t kOptionsComponentsCount = 0;

constexpr const char * kOptionsTextBindings[] = {
	nullptr,
};
constexpr std::size_t kOptionsTextBindingsCount = 0;

constexpr const char * kOptionsActions[] = {
	"options.controls",
	"options.display",
	"options.audio",
	"options.back",
};
constexpr std::size_t kOptionsActionsCount = 4;

constexpr const char * kOptionsDisplayComponents[] = {
	"options_display.fullscreen_indicator",
	"options_display.smooth_scaling_indicator",
};
constexpr std::size_t kOptionsDisplayComponentsCount = 2;

constexpr const char * kOptionsDisplayTextBindings[] = {
	nullptr,
};
constexpr std::size_t kOptionsDisplayTextBindingsCount = 0;

constexpr const char * kOptionsDisplayActions[] = {
	"options_display.fullscreen",
	"options_display.smooth_scaling",
	"options_display.save",
	"options_display.cancel",
};
constexpr std::size_t kOptionsDisplayActionsCount = 4;

constexpr const char * kOptionsAudioComponents[] = {
	"options_audio.music_indicator",
};
constexpr std::size_t kOptionsAudioComponentsCount = 1;

constexpr const char * kOptionsAudioTextBindings[] = {
	nullptr,
};
constexpr std::size_t kOptionsAudioTextBindingsCount = 0;

constexpr const char * kOptionsAudioActions[] = {
	"options_audio.music",
	"options_audio.save",
	"options_audio.cancel",
};
constexpr std::size_t kOptionsAudioActionsCount = 3;

struct SurfaceTokens {
	const char * surface;
	const char * const * components;
	std::size_t componentCount;
	const char * const * textBindings;
	std::size_t textBindingCount;
	const char * const * actions;
	std::size_t actionCount;
};

constexpr SurfaceTokens kSurfaceTokens[] = {
	{ kUiSurfaceMainMenu, kMainMenuComponents, kMainMenuComponentsCount, kMainMenuTextBindings, kMainMenuTextBindingsCount, kMainMenuActions, kMainMenuActionsCount },
	{ kUiSurfaceOptions, kOptionsComponents, kOptionsComponentsCount, kOptionsTextBindings, kOptionsTextBindingsCount, kOptionsActions, kOptionsActionsCount },
	{ kUiSurfaceOptionsDisplay, kOptionsDisplayComponents, kOptionsDisplayComponentsCount, kOptionsDisplayTextBindings, kOptionsDisplayTextBindingsCount, kOptionsDisplayActions, kOptionsDisplayActionsCount },
	{ kUiSurfaceOptionsAudio, kOptionsAudioComponents, kOptionsAudioComponentsCount, kOptionsAudioTextBindings, kOptionsAudioTextBindingsCount, kOptionsAudioActions, kOptionsAudioActionsCount },
};
constexpr std::size_t kSurfaceTokensCount = 4;

}  // namespace ui_layout_contract
}  // namespace net
}  // namespace silencer

#endif
