
















































































































































































































































































































> 1 	"Escape"	1 

> 2 	"Minus"	12 
> 3 	"Plus"	13 
> 4 	"Backspace"	14 
> 5 	"Tab"	15 

> 6 	"Left Brkt"	26 
> 7 	"Right Brkt"	27 
> 8 	"Enter"	28 
> 9 	"Left Ctrl"	29 
> 10 	"Semicolon"	39 
> 11 	"Quote"	40 
> 12 	"Tilde"	41 
> 13 	"Left Shift"	42 
> 14 	"Bk Slash"	43 

> 15 	"Less Than"	51 
> 16 	"Grtr Than"	52 
> 17 	"Fw Slash"	53 
> 18 	"Right Shift"	54 
> 19 	"Num Star"	55 
> 20 	"Left Alt"	56 
> 21 	"Space"	57 
> 22 	"Caps Lock"	58 

> 23 	"Num Lock"	69 
> 24 	"Scroll Lock"	70 
> 25 	"Num 7"	71 
> 26 	"Num 8"	72 
> 27 	"Num 9"	73 
> 28 	"Num Minus"	74 
> 29 	"Num 4"	75 
> 30 	"Num 5"	76 
> 31 	"Num 6"	77 
> 32 	"Num Plus"	78 
> 33 	"Num 1"	79 
> 34 	"Num 2"	80 
> 35 	"Num 3"	81 
> 36 	"Num Insert"	82 
> 37 	"Num Delete"	83 

> 38 	"Num Enter"	156 
> 39 	"Right Ctrl"	157 
> 40 	"Num Slash"	181 
> 41 	"Print Screen"	183 
> 42 	"Right Alt"	184 
> 43 	"Home"	199 
> 44 	"Up"	200 
> 45 	"Page Up"	201 
> 46 	"Left"	203 
> 47 	"Right"	205 
> 48 	"End"	207 
> 49 	"Down"	208 
> 50 	"Page Down"	209 
> 51 	"Insert"	210 
> 52 	"Delete"	211 

> 53 	"1"	2 
> 54 	"2"	3 
> 55 	"3"	4 
> 56 	"4"	5 
> 57 	"5"	6 
> 58 	"6"	7 
> 59 	"7"	8 
> 60 	"8"	9 
> 61 	"9"	10 
> 62 	"0"	11 

> 63 	"A"	30 
> 64 	"B"	48 
> 65 	"C"	46 
> 66 	"D"	32 
> 67 	"E"	18 
> 68 	"F"	33 
> 69 	"G"	34 
> 70 	"H"	35 
> 71 	"I"	23 
> 72 	"J"	36 
> 73 	"K"	37 
> 74 	"L"	38 
> 75 	"M"	50 
> 76 	"N"	49 
> 77 	"O"	24 
> 78 	"P"	25 
> 79 	"Q"	16 
> 80 	"R"	19 
> 81 	"S"	31 
> 82 	"T"	20 
> 83 	"U"	22 
> 84 	"V"	47 
> 85 	"W"	17 
> 86 	"X"	45 
> 87 	"Y"	21 
> 88 	"Z"	44 

> 89 	"F1"	59 
> 90 	"F2"	60 
> 91 	"F3"	61 
> 92 	"F4"	62 
> 93 	"F5"	63 
> 94 	"F6"	64 
> 95 	"F7"	65 
> 96 	"F8"	66 
> 97 	"F9"	67 
> 98 	"F10"	68 
> 99 	"F11"	87 
> 100 	"F12"	88 

> 103 	"Gamepad Lf"	-1
> 104 	"Gamepad Rt"	-1
> 105 	"Gamepad Up"	-1
> 106 	"Gamepad Dn"	-1

> 107 	"Gamepad UL"	-1
> 108 	"Gamepad UR"	-1
> 109 	"Gamepad DL"	-1
> 110 	"Gamepad DR"	-1

> 111 	"Gamepad B1"	-1
> 112 	"Gamepad B2"	-1
> 113 	"Gamepad B3"	-1
> 114 	"Gamepad B4"	-1
> 115 	"Gamepad B5"	-1
> 116 	"Gamepad B6"	-1
> 117 	"Gamepad B7"	-1
> 118 	"Gamepad B8"	-1
> 119 	"Gamepad B9"	-1
> 120 	"Gamepad B10"	-1
> 121 	"Gamepad B11"	-1
> 122 	"Gamepad B12"	-1
> 123 	"Gamepad B13"	-1
> 124 	"Gamepad B14"	-1
> 125 	"Gamepad B15"	-1
> 126 	"Gamepad B16"	-1

