




































































































> 1 	"I - Player Movement"	20 	1	1	0 
. "Basic control of your agent"

> 2 	"II - Agent Base"	20 	1	1	11 
. "Building and operating an agent base"

> 3 	"III - Secret Recovery"	20 	1	1	23 
. "Recovering secrets for your agency"

> 4 	"Area Star"	17 	1	0	-1 
. "Collect 3 top secrets"

> 5 	"Area Pyramid"	21 	1	0	-1 
. "Collect 3 top secrets"

> 6 	"Area towers"	24 	1	0	-1 
. "Collect 3 top secrets"

> 7 	"Area bomb pit"	10 	1	0	-1 
. "Collect 3 top secrets"

> 8 	"Area rocket alley"	2 	1	0	-1 
. "Collect 3 top secrets"


