import { existsSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";

import {
  UI_CONTAINER_NODE_KINDS,
  UI_DOCUMENT_FIELDS,
  UI_FLOATING_FIELDS,
  UI_IMAGE_FIELDS,
  UI_NODE_FIELDS,
  UI_NODE_KINDS,
  UI_SIZE_FIELDS,
  UI_STYLE_FIELDS_BY_KIND,
  UI_VIEWPORT_FIELDS,
} from "../contract";

const HEADER_PATH = join(
  import.meta.dir,
  "../../../clients/silencer/src/net/ui_layout_contract.generated.h",
);

function cppString(value: string): string {
  return `"${value.replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"`;
}

function cppArray(name: string, values: readonly string[]): string {
  const items = values.map((value) => `\t${cppString(value)},`).join("\n");
  return `constexpr const char * ${name}[] = {\n${items}\n};\nconstexpr std::size_t ${name}Count = ${values.length};`;
}

function pascalCase(value: string): string {
  return value
    .split(/[^a-zA-Z0-9]+/g)
    .filter(Boolean)
    .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
    .join("");
}

function styleFieldArrays(): string {
  const arrays = UI_NODE_KINDS.map((kind) =>
    cppArray(`k${pascalCase(kind)}StyleFields`, UI_STYLE_FIELDS_BY_KIND[kind]),
  ).join("\n\n");
  const rows = UI_NODE_KINDS.map((kind) => {
    const name = `k${pascalCase(kind)}StyleFields`;
    return `\t{ ${cppString(kind)}, ${name}, ${name}Count },`;
  }).join("\n");
  return `${arrays}

struct StyleFieldsForKind {
\tconst char * kind;
\tconst char * const * fields;
\tstd::size_t fieldCount;
};

constexpr StyleFieldsForKind kStyleFieldsByKind[] = {
${rows}
};
constexpr std::size_t kStyleFieldsByKindCount = ${UI_NODE_KINDS.length};`;
}

function generateHeader(): string {
  return `// Generated by shared/ui-layout/tools/generate-ui-layout-contract.ts.
// Do not edit by hand.

#ifndef SILENCER_NET_UI_LAYOUT_CONTRACT_GENERATED_H
#define SILENCER_NET_UI_LAYOUT_CONTRACT_GENERATED_H

#include <cstddef>

namespace silencer {
namespace net {
namespace ui_layout_contract {

${cppArray("kNodeKinds", UI_NODE_KINDS)}

${cppArray("kContainerNodeKinds", UI_CONTAINER_NODE_KINDS)}

${cppArray("kDocumentFields", UI_DOCUMENT_FIELDS)}

${cppArray("kViewportFields", UI_VIEWPORT_FIELDS)}

${cppArray("kNodeFields", UI_NODE_FIELDS)}

${cppArray("kSizeFields", UI_SIZE_FIELDS)}

${cppArray("kImageFields", UI_IMAGE_FIELDS)}

${cppArray("kFloatingFields", UI_FLOATING_FIELDS)}

${styleFieldArrays()}

}  // namespace ui_layout_contract
}  // namespace net
}  // namespace silencer

#endif
`;
}

const generated = generateHeader();
if (process.argv.includes("--check")) {
  const current = existsSync(HEADER_PATH) ? readFileSync(HEADER_PATH, "utf8") : "";
  if (current !== generated) {
    console.error(`UI layout C++ contract is stale: ${HEADER_PATH}`);
    console.error("Run: bun run --filter @silencer/ui-layout generate-contract");
    process.exit(1);
  }
} else {
  writeFileSync(HEADER_PATH, generated);
}
