#ifndef OBJECT_TYPES
#define OBJECT_TYPES

#include "shared.h"

class ObjectTypes
{
public:
	ObjectTypes();
	class Object * CreateFromType(Uint8 type);
	unsigned int SerializedSize(Uint8 type);
	enum {OVERLAY, RESERVED_UI_1, RESERVED_UI_2, RESERVED_UI_3, RESERVED_UI_4, RESERVED_UI_5, RESERVED_UI_6, RESERVED_UI_7, STATE,
		TEAM, PLAYER, CIVILIAN, GUARD, ROBOT, TERMINAL, VENT, HEALMACHINE,
		CREDITMACHINE, SECRETRETURN, SURVEILLANCEMONITOR, TECHSTATION, INVENTORYSTATION, TEAMBILLBOARD,
		PLUME, SHRAPNEL, BODYPART, BLASTERPROJECTILE, LASERPROJECTILE, ROCKETPROJECTILE, FLAMERPROJECTILE,
		PLASMAPROJECTILE, FLAREPROJECTILE, WALLPROJECTILE, BASEDOOR, PICKUP, WARPER, DETONATOR,
		FIXEDCANNON, GRENADE, WALLDEFENSE, BASEEXIT, MAX_OBJECT_TYPE};

private:
	unsigned int serializedsize[0xFF];
};

#endif
